fix: language selection was not taken seriously
Innoactive/Creator-Base-Template pull request #99
Opened 2020-09-02 09:05 UTC by SimonTheSourcerer

### Description
Seems like text to speech configuration was not considered when the language selection was displayed so we always switched to default. Also switching between languages was not reflected in the text to speech config. Fixed that.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
* Manually

2020-09-02 11:52 UTC, Gusinuhe reviewed
Can you also fix [StandaloneCourseController](https://github.com/Innoactive/Creator-Base-Template/blob/develop/Runtime/CourseController/StandaloneCourseController.cs)?

2020-09-03 21:37 UTC, Maxsiom commented
Updated and tested. Works perfectly for me :)

2020-09-03 22:07 UTC, Maxsiom commented
Failed tests are fixed here: https://github.com/Innoactive/XR-Interaction-Component/pull/54

2020-09-06 10:31 UTC, Gusinuhe requested changes
I don´t know what is it, but there is something in this PR that breaks cached TTS in Oculus Quest (Android).

2020-09-06 10:44 UTC, Gusinuhe commented
This can be tested in any Android device with the following configuration:

- Do not add any XR configuration to the project, if there is one, remove it.
- Do not add the [XR_Setup] prefab, if it already exists delete it and set a new unity Camera.
- Add a `GameObject > UI > Event System`
- Make sure the `[COURSE_CONTROLLER]` is set to `Default`.
- Build an Android application (no special configuration required).

Use the `DefaultCourseController` to skip steps (you should be able to just click on the buttons).

2020-09-07 18:11 UTC, Maxsiom commented
Is it the .Net compatibility issue?

2020-09-07 19:11 UTC, Gusinuhe commented
> Is it the .Net compatibility issue?

It could be, I never tested with .net 4.x, only with .net 2.0

2020-09-23 13:15 UTC, Gusinuhe approved these changes
Yeah, ok, Android issues are being addressed in another PR.

2020-10-08 09:59 UTC, Maxsiom approved these changes

2020-10-08 09:59 UTC, merged